import { PokemonLocationData } from "../../locations";

export const kindleRoad: PokemonLocationData = {
    catchMap: {
        Cave: {
            Spearow: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 30,
                maxLevel: 32,
                rate: 25,
            },
            Fearow: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 36,
                maxLevel: 36,
                rate: 10,
            },
            Meowth: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 31,
                maxLevel: 31,
                rate: 10,
            },
            Persian: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 37,
                maxLevel: 40,
                rate: 5,
            },
            Psyduck: {
                inFireRed: true,
                inLeafGreen: false,
                minLevel: 34,
                maxLevel: 34,
                rate: 5,
            },
            Geodude: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 31,
                maxLevel: 31,
                rate: 10,
            },
            Ponyta: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 31,
                maxLevel: 34,
                rate: 30,
            },
            Rapidash: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 37,
                maxLevel: 40,
                rate: 5,
            },
            Slowpoke: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 34,
                maxLevel: 34,
                rate: 5,
            },
        },
        Surfing: {
            Tentacool: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 5,
                maxLevel: 40,
                rate: 95,
            },
            Tentacruel: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 55,
                maxLevel: 40,
                rate: 5,
            },
        },
        "Old Rod": {
            Magikarp: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 5,
                maxLevel: 5,
                rate: 100,
            },
        },
        "Good Rod": {
            Krabby: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 5,
                maxLevel: 15,
                rate: 80,
            },
            Horsea: {
                inFireRed: true,
                inLeafGreen: false,
                minLevel: 5,
                maxLevel: 15,
                rate: 80,
            },
            Magikarp: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 5,
                maxLevel: 15,
                rate: 80,
            },
        },
        "Super Rod": {
            Psyduck: {
                inFireRed: true,
                inLeafGreen: false,
                minLevel: 25,
                maxLevel: 35,
                rate: 1,
            },
            Slowpoke: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 25,
                maxLevel: 35,
                rate: 1,
            },
            Krabby: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 15,
                maxLevel: 35,
                rate: 80,
            },
            Kingler: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 25,
                maxLevel: 35,
                rate: 4,
            },
            Horsea: {
                inFireRed: true,
                inLeafGreen: false,
                minLevel: 15,
                maxLevel: 35,
                rate: 80,
            },
            Seadra: {
                inFireRed: false,
                inLeafGreen: true,
                minLevel: 25,
                maxLevel: 35,
                rate: 4,
            },
            Gyarados: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 15,
                maxLevel: 25,
                rate: 15,
            },
        },
        "Rock Smash": {
            Geodude: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 5,
                maxLevel: 30,
                rate: 95,
            },
            Graveler: {
                inFireRed: true,
                inLeafGreen: true,
                minLevel: 25,
                maxLevel: 40,
                rate: 5,
            },
        },
    },
    connections: [
        "Mt. Ember",
        "One Island",
    ],
};
